name: attach development pipeline

on: workflow_dispatch
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update_and_deploy:
    uses: CuBoulder/action-collection/.github/workflows/sandbox-ci.yml@main
    secrets: inherit